# CSE 252B: Computer Vision II, Winter 2020 – Assignment 2

### Instructor: Ben Ochoa

### Due: Wednesday, February 5, 2020, 11:59 PM

## Instructions
* Review the academic integrity and collaboration policies on the course website.
* This assignment must be completed individually.
* This assignment contains both math and programming problems.
* All solutions must be written in this notebook
* Math must be done in Markdown/LaTeX.
* You must show your work and describe your solution.
* Programming aspects of this assignment must be completed using Python in this notebook.
* Your code should be well written with sufficient comments to understand, but there is no need to write extra markdown to describe your solution if it is not explictly asked for.
* This notebook contains skeleton code, which should not be modified (This is important for standardization to facilate efficient grading).
* You may use python packages for basic linear algebra, but you may not use packages that directly solve the problem. If you are uncertain about using a specific package, then please ask the instructional staff whether or not it is allowable.
* You must submit this notebook exported as a pdf. You must also submit this notebook as an .ipynb file.
* Your code and results should remain inline in the pdf (Do not move your code to an appendix).
* You must submit both files (.pdf and .ipynb) on Gradescope. You must mark each problem on Gradescope in the pdf.
* It is highly recommended that you begin working on this assignment early.

## Problem 1 (Math): Line-plane intersection (5 points)
  The line in 3D defined by the join of the points $\boldsymbol{X}_1 = (X_1,
  Y_1, Z_1, T_1)^\top$ and $\boldsymbol{X}_2 = (X_2, Y_2, Z_2, T_2)^\top$
  can be represented as a Plucker matrix $\boldsymbol{L} = \boldsymbol{X}_1
  \boldsymbol{X}_2^\top - \boldsymbol{X}_2 \boldsymbol{X}_1^\top$ or pencil of points
  $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 - \lambda) \boldsymbol{X}_2$
  (i.e., $\boldsymbol{X}$ is a function of $\lambda$).  The line intersects
  the plane $\boldsymbol{\pi} = (a, b, c, d)^\top$ at the point
  $\boldsymbol{X}_{\boldsymbol{L}} = \boldsymbol{L} \boldsymbol{\pi}$ or
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$, where $\lambda_{\boldsymbol{\pi}}$ is
  determined such that $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})^\top \boldsymbol{\pi} =
  0$ (i.e., $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ is the point on
  $\boldsymbol{\pi}$).  Show that $\boldsymbol{X}_{\boldsymbol{L}}$ is equal to
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ up to scale.

Your solution here: 
${X}_{L} = L \pi = (X_{1}X_{2}^{T} - X_{2}X_{1}^{T}) \pi = X_{1}X_{2}^{T}\pi$ , since $X^{T}\pi$ is constance, the equation becomes ${X}_{L} = a X_1 + bX_1 = \lambda X_{1} + (1-\lambda)X_2$ up to scale.




## Problem 2 (Math): Line-quadric intersection (5 points)
  In general, a line in 3D intersects a quadric $\boldsymbol{Q}$ at zero, one
  (if the line is tangent to the quadric), or two points.  If the
  pencil of points $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 -
  \lambda) \boldsymbol{X}_2$ represents a line in 3D, the (up to two) real
  roots of the quadratic polynomial $c_2 \lambda_{\boldsymbol{Q}}^2 + c_1
  \lambda_{\boldsymbol{Q}} + c_0 = 0$ are used to solve for the intersection
  point(s) $\boldsymbol{X}(\lambda_{\boldsymbol{Q}})$.  Show that $c_2 =
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q}
  \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$, $c_1 = 2 (
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q}
  \boldsymbol{X}_2 )$, and $c_0 = \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$.

Your solution here:
If $X(\lambda_{Q})$ intersects with a quadric $Q$, then $X(\lambda_Q)^TQX(\lambda_Q) = 0$, also we have a line crossing $X1$, $X2$ on Quadric $X(\lambda_Q) = \lambda_{Q} X_1+(1-\lambda_{Q})X_2$.
Therefore, $(\lambda_{Q}X_{1}^{T}Q + (1-\lambda_Q)X_{2}^{T}Q)(\lambda_{Q}X_{1} + (1-\lambda_{Q})X_{2})$ = 

= $\lambda_{Q}^2 {X}_1^T{Q} X_1 + (1 - \lambda_Q) \lambda_Q {X}_2^T{Q} {X}_1 + (1 - \lambda_{{Q}}) \lambda_{{Q}}{X}_1^T {Q} {X}_2 + (1 - \lambda_{{Q}})^2 {X}_2^T {Q} {X}_2 ) $

= $ \lambda_{\boldsymbol{Q}}^2({X}_1^T {Q} {X}_1 - {X}_2^T {Q} {X}_1 - {X}_1^T {Q} {X}_2 + {X}_2^T {Q} {X}_2) +  \lambda_{{Q}}({X}_2^T {Q} {X}_1 + {X}_1^T {Q} {X}_2 - 2{X}_2^T {Q} {X}_2) + ({X}_2^T {Q} {X}_2)$

= $ \lambda_{{Q}}^2({X}_1^T {Q} {X}_1 - 2{X}_1^T {Q} {X}_2 + {X}_2^T {Q} {X}_2) +  \lambda_{Q}^{2}({X}_1^T {Q} {X}_2 -  {X}_2^T {Q} {X}_2) + ({X}_2^T {Q} {X}_2)$

= $c_2 \lambda_{{Q}}^2 + c_1
  \lambda_{{Q}} + c_0 = 0$
  
Therefore, $c_2 =
  {X}_1^T {Q} {X}_1 - 2 {X}_1^T {Q}
  {X}_2 + {X}_2^T {Q} {X}_2$, $c_1 = 2 (
  {X}_1^T {Q} {X}_2 - {X}_2^T {Q}
  {X}_2 )$, and $c_0 = {X}_2^T {Q} {X}_2$.




## Problem 3 (Programming):  Linear Estimation of the Camera Projection Matrix (15 points)
  Download input data from the course website.  The file
  hw2_points3D.txt contains the coordinates of 50 scene points
  in 3D (each line of the file gives the $\tilde{X}_i$, $\tilde{Y}_i$,
  and $\tilde{Z}_i$ inhomogeneous coordinates of a point).  The file
  hw2_points2D.txt contains the coordinates of the 50
  corresponding image points in 2D (each line of the file gives the
  $\tilde{x}_i$ and $\tilde{y}_i$ inhomogeneous coordinates of a
  point).  The scene points have been randomly generated and projected
  to image points under a camera projection matrix (i.e., $\boldsymbol{x}_i
  = \boldsymbol{P} \boldsymbol{X}_i$), then noise has been added to the image point
  coordinates.

  Estimate the camera projection matrix $\boldsymbol{P}_\text{DLT}$ using the
  direct linear transformation (DLT) algorithm (with data
  normalization).  You must express $\boldsymbol{x}_i = \boldsymbol{P} \boldsymbol{X}_i$
  as $[\boldsymbol{x}_i]^\perp \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$ (not
  $\boldsymbol{x}_i \times \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$), where
  $[\boldsymbol{x}_i]^\perp \boldsymbol{x}_i = \boldsymbol{0}$, when forming the
  solution. Return
  $\boldsymbol{P}_\text{DLT}$, scaled such that
  $||\boldsymbol{P}_\text{DLT}||_\text{Fro} = 1$
  
  The following helper functions may be useful in your DLT function implementation.
  You are welcome to add any additional helper functions.

In [172]:
import numpy as np
import time

def Homogenize(x):
    # converts points from inhomogeneous to homogeneous coordinates
    #print("shape of x: {}".format(x.shape))
    return np.vstack((x,np.ones((1,x.shape[1]))))


def Dehomogenize(x):
    # converts points from homogeneous to inhomogeneous coordinates
    return x[:-1]/x[-1]


def Normalize(pts):
    # data normalization of n dimensional pts
    #
    # Input:
    #    pts - is in inhomogeneous coordinates
    # Outputs:
    #    pts - data normalized points
    #    T - corresponding transformation matrix
    """your code here"""
    
    T = np.eye(pts.shape[0]+1)
    if pts.shape[0] == 2:
        means = np.mean(pts, axis = 1)
        _vars = np.var(pts, axis = 1)
        var = np.sum(_vars)
        scale = math.sqrt(2/var)
        T[0,0] = scale
        T[1,1] = scale
        T[0,2] = -means[0] * scale
        T[1,2] = -means[1] * scale
    
    if pts.shape[0] == 3:
        means= np.mean(pts, axis = 1)
        _vars= np.var(pts, axis = 1)
        var = np.sum(_vars)
        scale = math.sqrt(3/var)
        T[0,0] = scale
        T[1,1] = scale
        T[2,2] = scale
        T[0,3] = -means[0] * scale
        T[1,3] = -means[1] * scale
        T[2,3] = -means[2] * scale
    pts = np.dot(T, Homogenize(pts))
    return pts, T

def ComputeCost(P, x, X):
    # Inputs:
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #
    # Output:
    #    cost - Total reprojection error
    
    n = x.shape[1]
    covarx = np.eye(2*n)
    
    """your code here"""
    
    x_pred = np.dot(P,Homogenize(X))
    x_pred = Dehomogenize(x_pred)
    cost = np.sum((x_pred - x)**2)
    return cost


In [173]:
def leftnull(sub_x):
    sub_x = np.reshape(sub_x,(sub_x.size,1))
    u, _, _ = np.linalg.svd(sub_x,full_matrices=True)
    _leftnull = u[:,1:].T
    return _leftnull

def DLT(x, X, normalize=True):
    # Inputs:
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    normalize - if True, apply data normalization to x and X
    #
    # Output:
    #    P - the (3x4) DLT estimate of the camera projection matrix
    P = np.eye(3,4)+np.random.randn(3,4)/10
        
    # data normalization
    n = x.shape[1]
    if normalize:
        x, T = Normalize(x)
        X, U = Normalize(X)
    else:
        x = Homogenize(x)
        X = Homogenize(X)
    
    """your code here"""
    
    A = np.zeros((2*n,12))
    for i in range(n):
        _leftnull = leftnull(x[:,i])
        sub_A = np.kron(_leftnull,X[:,i].T)
        A[2*i:2*i+2,:] = sub_A
    u, s, vh = np.linalg.svd(A, full_matrices=False)
    P_flatten = vh[-1,:]
    P = P_flatten.reshape((P.shape))
    # data denormalize
    if normalize:
        P = np.linalg.inv(T) @ P @ U
        
    return P

def displayResults(P, x, X, title):
    print(title+' =')
    print (P/np.linalg.norm(P)*np.sign(P[-1,-1]))

# load the data
x=np.loadtxt('hw2_points2D.txt').T
X=np.loadtxt('hw2_points3D.txt').T


# compute the linear estimate without data normalization
print ('Running DLT without data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=False)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)

# compute the linear estimate with data normalization
print ('Running DLT with data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=True)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)

print("\n==Correct outputs==")
print("Cost=%.9f without data normalization"%97.053718991)
print("Cost=%.9f with data normalization"%84.104680130)

Running DLT without data normalization
took 0.010492 secs
Cost=97.053718998
Running DLT with data normalization
took 0.011197 secs
Cost=84.104680130

==Correct outputs==
Cost=97.053718991 without data normalization
Cost=84.104680130 with data normalization


In [174]:
# Report your P_DLT value here!
displayResults(P_DLT, x, X, 'P_DLT')

P_DLT =
[[ 6.04350846e-03 -4.84282446e-03  8.82395315e-03  8.40441373e-01]
 [ 9.09666810e-03 -2.30374203e-03 -6.18060233e-03  5.41657305e-01]
 [ 5.00625470e-06  4.47558354e-06  2.55223773e-06  1.25160752e-03]]


## Problem 4 (Programming):  Nonlinear Estimation of the Camera Projection Matrix (30 points)
  Use $\boldsymbol{P}_\text{DLT}$ as an initial estimate to an iterative
  estimation method, specifically the Levenberg-Marquardt algorithm,
  to determine the Maximum Likelihood estimate of the camera
  projection matrix that minimizes the projection error.  You must
  parameterize the camera projection matrix as a parameterization of
  the homogeneous vector $\boldsymbol{p} = vec{(\boldsymbol{P}^\top)}$.  It is
  highly recommended to implement a parameterization of homogeneous
  vector method where the homogeneous vector is of arbitrary length,
  as this will be used in following assignments.
  
  Report the initial cost (i.e. cost at iteration 0) and the cost at the end
  of each successive iteration. Show the numerical values for the final 
  estimate of the camera projection matrix $\boldsymbol{P}_\text{LM}$, scaled
  such that $||\boldsymbol{P}_\text{LM}||_\text{Fro} = 1$.
  
  The following helper functions may be useful in your LM function implementation.
  You are welcome <i>and encouraged</i> to add any additional helper functions.
  
  Hint: LM has its biggest cost reduction after the 1st iteration. You'll know if you 
  are implementing LM correctly if you experience this.

In [175]:
# Note that np.sinc is different than defined in class
import math
def Sinc(x):
    # Returns a scalar valued sinc value
    """your code here"""
    if x == 0:
        y = 1
    else:
        y = math.sin(x)/x
    return y

def Jacobian(P,p,X):
    # compute the jacobian matrix
    #
    # Input:
    #    P - 3x4 projection matrix
    #    p - 11x1 homogeneous parameterization of P
    #    X - 3xn 3D scene points
    # Output:
    #    J - 2nx11 jacobian matrix
    J = np.zeros((2*X.shape[1],11))
    
    """your code here"""
    X = Homogenize(X)
    x = np.dot(P,X)
    x_de = Dehomogenize(x)
    p_bar = P.reshape(12,1)
    for i in range(X.shape[1]):
        pt_cur = X[:,i]
        w = np.dot(P[-1,:],pt_cur)
        dx_dp = np.zeros((2,12))
        dx_dp[0,:4] = dx_dp[1,4:8] = pt_cur.T
        dx_dp[0,8:] = -x_de[0][i] * pt_cur.T
        dx_dp[1,8:] = -x_de[1][i] * pt_cur.T
        dx_dp = (1/w)* dx_dp
        
        a = p_bar[0,0]
        b = p_bar[1:,0]
        norm_p = np.linalg.norm(p)
        if  norm_p == 0:
            da_dv = np.zeros((1,11))
            db_dv = 0.5*np.eye(11)
        else:
            da_dv = -0.5 * b.T
            half_norm = norm_p / 2
            tmp = math.cos(half_norm)/ half_norm - 
            math.sin(half_norm)/ (half_norm**2)
            db_dv = Sinc(half_norm)* np.eye(11)/ 2 + 
            1/(4*norm_p)*tmp * np.dot(p,p.T)
        dp_dp = np.vstack((da_dv,db_dv))
        Ai = np.dot(dx_dp,dp_dp)
        J[2*i:2*i+2,:] = Ai
    return J

def Parameterize(P):
    # wrapper function to interface with LM
    # takes all optimization variables and parameterizes all of them
    # in this case it is just P, but in future assignments it will
    # be more useful
    #print("shape of P:{}".format(P.shape))
    return ParameterizeHomog(P.reshape(-1,1))

def Deparameterize(p):
    # Deparameterize all optimization variables
    return DeParameterizeHomog(p).reshape(3,4)

def ParameterizeHomog(V):
    # Given a homogeneous vector V return its minimal parameterization
    """your code here"""
    v = V / np.linalg.norm(V)
    #print("shape of v: {},v:{}".format(v.shape,v))
    a = v[0][0]
    b = v[1:,:]
    v_hat = 2/(Sinc(math.acos(a)))*b
    v_norm = np.linalg.norm(v_hat)
    if v_norm > math.pi:
        scale = 1-(2*math.pi/v_norm)*
                math.ceil((v_norm - math.pi)/(2*math.pi))
        v_hat = scale * v_hat
    return v_hat

def DeParameterizeHomog(v):
    # Given a parameterized homogeneous vector return its deparameterization
    """your code here"""
    v_norm = np.linalg.norm(v)
    a = math.cos(v_norm/2)
    b = Sinc(v_norm /2 )*0.5 * v.T
    v_bar = np.zeros((v.shape[0]+1,1))
    v_bar[0,0] = a
    v_bar[1:v.shape[0]+1,:] = b.T
    v_bar = v_bar/ np.linalg.norm(v_bar)
    return v_bar


In [176]:
def LM(P, x, X, max_iters, lam):
    # Input:
    #    P - initial estimate of P
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    max_iters - maximum number of iterations
    #    lam - lambda parameter
    # Output:
    #    P - Final P (3x4) obtained after convergence
    
    # data normalization
    x, T = Normalize(x)
    X, U = Normalize(X)
    """your code here"""
    P = np.dot(np.dot(T,P),np.linalg.inv(U))
    p = Parameterize(P)
    x_hat = np.dot(P, X)
    # you may modify this so long as the cost is computed
    # at each iteration
    error = Dehomogenize(x) - Dehomogenize(x_hat)
    error = np.reshape(error, (2*x.shape[1],-1), order = 'F')
    sigma = (T[0,0]**2)* np.eye(2*x.shape[1]) 
    sigma_inv = np.linalg.inv(sigma)
    i = 0
    lam_explode = 1e10
    while i < max_iters: 
        J = Jacobian(Deparameterize(p),p,Dehomogenize(X))
        normal_matrix = np.dot(np.dot(J.T,sigma_inv),J) + lam*np.eye(11)
        normal_vector = np.dot(np.dot(J.T,sigma_inv), error)
        normal_matrix_inv = np.linalg.inv(normal_matrix)
        delta = np.dot(normal_matrix_inv,normal_vector)
        p0 = p + delta
        P0 = Deparameterize(p0)
        x_hat0 = np.dot(P0,X)
        error0 = Dehomogenize(x) - Dehomogenize(x_hat0)
        error0 = np.reshape(error0, (2*x.shape[1],-1), order = 'F')
        cost0 = np.dot(np.dot(error0.T, sigma_inv), error0)
        cost_pre = np.dot(np.dot(error.T, sigma_inv), error)
        if(cost0 < cost_pre):
            lam = 0.1*lam
            p = p0
            error = error0
            i += 1
            cost_pre = cost0
            cost = cost0
            print ('iter %03d Cost %.9f'%(i, cost))
        else:
            lam = 10* lam
            cost = cost_pre
        if lam > lam_explode:
            break
    # data denormalization
    P = np.linalg.inv(T) @ P0 @ U
    
    return P



# LM hyperparameters
lam = .001
max_iters = 100
x=np.loadtxt('hw2_points2D.txt').T
X=np.loadtxt('hw2_points3D.txt').T
P_DLT = DLT(x, X, normalize=True)
# Run LM initialized by DLT estimate with data normalization
print ('Running LM with data normalization')
print ('iter %03d Cost %.9f'%(0, cost))
time_start=time.time()
P_LM = LM(P_DLT, x, X, max_iters, lam)
time_total=time.time()-time_start
print('took %f secs'%time_total)

print("\n==Correct outputs==")
print("Begins at %.9f; ends at %.9f"%(84.104680130, 82.790238005))

Running LM with data normalization
iter 000 Cost 84.104680130
iter 001 Cost 82.791336044
iter 002 Cost 82.790238006
iter 003 Cost 82.790238005
iter 004 Cost 82.790238005
iter 005 Cost 82.790238005
took 0.068347 secs

==Correct outputs==
Begins at 84.104680130; ends at 82.790238005


In [177]:
# Report your P_LM final value here!
displayResults(P_LM, x, X, 'P_LM')

P_LM =
[[ 6.09434291e-03 -4.72647758e-03  8.79023503e-03  8.43642842e-01]
 [ 9.02017241e-03 -2.29290824e-03 -6.13330068e-03  5.36660248e-01]
 [ 4.99088611e-06  4.45205073e-06  2.53705045e-06  1.24348254e-03]]
